cosmology:
  H0 : 67.7 
  ombh2 : 0.022458
  omch2 :  0.142586
  mnu : 0.00
  omk : 0.0 
  tau : 0.054

initpower:
  As : 2.105e-09
  ns : 0.9665
  r : 0.0

set_matterpower:
  redshifts : [0.]
  kmax : 100
  silent : True

get_matterpower:
  minkh : 1.e-4
  maxkh : 0.25 
  npoints : 10000